name: react-ci
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.2.0'
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn build
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.2.0'
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn test
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.2.0'
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn fmt
